<?php

declare(strict_types=1);

namespace justinholtweb\owl\records;

use craft\db\ActiveRecord;

/**
 * A materialised occurrence of an event. Plain rows (not elements) keyed by the canonical event id,
 * so multisite does not multiply the occurrence count. Generated by the recurrence engine up to the
 * configured rolling horizon and queried directly for fast, paginatable calendar range lookups.
 *
 * @property int $id
 * @property int $eventId
 * @property string $startDate UTC
 * @property string $endDate UTC
 * @property bool $allDay
 * @property bool $isException
 * @property bool $isOverride
 * @property string|null $overrideData JSON
 */
class OccurrenceRecord extends ActiveRecord
{
    public static function tableName(): string
    {
        return '{{%owl_occurrences}}';
    }
}
